libjxl/jxl-rs

- AUTHORS
- src/headers/extra_channels.rs
- src/headers/image_metadata.rs
Hi! This is just a quick fix for some inconsistencies between the spec and the code (I checked libjxl code so I hope I'm not missing something...).
The change to `spot_color` should account for `solidity`.
> Fix inconsistencies when parsing ImageData.

- jxl_headers_derive/src/lib.rs
- src/error.rs
- src/headers.rs
- src/headers/bit_depth.rs
- src/headers/color_encoding.rs
- src/headers/encodings.rs
- src/headers/extra_channels.rs
- src/headers/frame_header.rs
- src/headers/image_metadata.rs
- src/main.rs
Hi ! This PR implements parsing of the frame headers.
To do that, I needed to change some of the `derive` code:
- `#[size_coder]` now accepts either `implicit(...)` or `explicit(...)`. Implicit will read the size from the `BitReader`, explicit uses some already decoded variable to get the size.
- I added a new attribute `#[aligned]` that calls `jump_to_byte_boundary()` before and after decoding the bundle.
- I removed the `abort` caused by using `#[default]` with `#[size_coder]`. It should work as-is as far as I can see, but let me know if I missed something.
> implemented FrameHeader parsing

- .github/workflows/pull_request.yml
- AUTHORS
A bit of CI maintenance, this PR updates the [checkout](https://github.com/actions/checkout) action to v3 and the [rust-cache](https://github.com/Swatinem/rust-cache) version to v2.0
> CI: Update checkout and rust-cache versions

- .github/workflows/pull_request.yml
- Update `actions/checkout` to v4.
- Update `Swatinem/rust-cache` to v2.7.3.
- Use `dtolnay/rust-toolchain` because `actions-rs/toolchain` is no longer maintained.
> Update GitHub Actions dependencies

- Cargo.toml
- ci/pull_request_checks.sh
- jxl/Cargo.toml
- jxl/src/headers/frame_header.rs
- jxl/src/image.rs
- jxl/src/lib.rs
- jxl/src/render/mod.rs
- jxl_cli/Cargo.toml
- jxl_headers_derive/Cargo.toml
Also add `#[deny(unsafe_code)]` to ensure that unsafe code is easier to audit, and missing_safety_doc, undocumented_unsafe_blocks, unsafe_op_in_unsafe_fn.
> Cleanup: fix pull_request_checks.sh, add missing headers.

- jxl/src/error.rs
- jxl/src/image.rs
- jxl/src/render/internal.rs
- jxl/src/render/mod.rs
- jxl/src/render/simple_pipeline.rs
- jxl/src/util.rs
- jxl/src/util/shift_right_ceil.rs
Also add f64 to the possible image types, use an explicit enum to tag image types, and rework the pipeline interface.
> Simple pipeline implementation.

- jxl/src/entropy_coding/ans.rs
- jxl/src/entropy_coding/context_map.rs
- jxl/src/entropy_coding/decode.rs
- jxl/src/error.rs
Mostly copied from jxl-oxide, and modified to eliminate `unsafe`. (Reading streams can be branchless with unchecked indexing and by transmuting `Bucket` to `u64`.)
> Implement decoding of ANS streams

- jxl/src/entropy_coding/decode.rs
- jxl/src/entropy_coding/huffman.rs
- jxl/src/entropy_coding/hybrid_uint.rs
- jxl/src/entropy_coding/lz77.rs
- jxl/src/entropy_coding/mod.rs
- jxl/src/error.rs
Add `Lz77ReaderInner` and wire things to support LZ77 stream decoding.
> Implement LZ77 decoding

- jxl/src/render/mod.rs
- jxl/src/render/simple_pipeline.rs
- jxl/src/render/stages/convert.rs
- jxl/src/render/stages/save.rs
- jxl/src/render/stages/upsample.rs
Use `Display::fmt` instead of separate `name` method, like [`std::error::Error`][error] does. (`.to_string()` can be used if `String` is needed.)
[error]: https://doc.rust-lang.org/stable/std/error/trait.Error.html
> Use `Display` to set render stage names

- jxl/src/error.rs
- jxl/src/headers/mod.rs
- jxl/src/headers/permutation.rs
- jxl/src/util.rs
- jxl/src/util/bits.rs
> Permutation decoding

- jxl/src/frame/modular.rs
Channels after the first "large" one are not in LF global; the existing code assumed decisions were made per channel.
> Fix modular channels section assignment.

- jxl/src/headers/transform_data.rs
- jxl/src/render/stages/mod.rs
- jxl/src/render/stages/xyb.rs
- jxl/src/util.rs
- jxl/src/util/linalg.rs
Implement F32 in-place XYB to linear sRGB stage.
> XYB to linear sRGB stage

- jxl/src/frame/modular.rs
- jxl/src/frame/modular/predict.rs
- jxl/src/frame/modular/transforms.rs
Also compute the relevant transforms "decomposed" to operate on grid chunks, and the dependencies in decoding (i.e. which inputs are needed for which transform).
> Add logic to compute channel grids for modular.

- jxl/src/color/tf.rs
- jxl/src/util/fast_math.rs
Implements HLG OETF and OOTF (and their inverses).
> Implement HLG transfer functions

- jxl/src/frame.rs
- jxl/src/frame/modular.rs
- jxl/src/frame/modular/decode.rs
- jxl/src/frame/modular/predict.rs
- jxl/src/frame/modular/transforms.rs
- jxl/src/frame/modular/tree.rs
- jxl/src/frame/quantizer.rs
- jxl/src/headers/frame_header.rs
Does not support the Weighted predictor or prev-channel properties yet, and is not optimized.
> Implement a first version of modular channel decoding.

- jxl/src/render/stages/apply_transfer.rs
- jxl/src/render/stages/mod.rs
Corresponds to `from_linear` of libjxl.
> Add `ApplyTransferStage`

- jxl/src/entropy_coding/huffman.rs
Symbols of simple Huffman table are used in the order they were read.
(Found while testing with my own testset)
> Fix reading simple Huffman table

- jxl/src/color/tf.rs
Updated the constant in `hlg_to_scene_precise` to match the equivalent upstream libjxl transfer function definitions.
Upstream Definitions: 
- https://github.com/libjxl/libjxl/blob/main/lib/jxl/cms/transfer_functions.h#L54-L64
- https://github.com/libjxl/libjxl/blob/main/lib/jxl/cms/transfer_functions-inl.h#L71-L83
> color/tf: Fix constant in hlg_to_scene_precise

- jxl/src/color/tf.rs
- jxl/src/render/stages/mod.rs
- jxl/src/render/stages/to_linear.rs
Other than adding a fastmath `hlg_to_scene` impl, changing the functions for the tf conversions, and reversing the test values for the test cases, this mostly just copies `FromLinearStage`.
I had to add some precision to the values for the `sdr_white_pq` test to get the tests to pass as the rounded values pick up just barely too much error when going in the reverse direction.
Given how much is similar between this and FromLinear, later on down the road we could fairly trivially collapse them into a single implementation and define the stages as type aliases off that base implementation.
> Implement ToLinearStage

- jxl/src/render/stages/to_linear.rs
I noticed when I was pulling a lot of the code from `from_linear.rs` I forgot to update some of the comments and debug text. This resolves that
> render/stages/to_linear.rs: Fixup descriptions

- jxl/src/lib.rs
- jxl/src/render/stages/epf.rs
- jxl/src/render/stages/mod.rs
- jxl/src/render/stages/spot.rs
- jxl/src/render/stages/ycbcr.rs
Just a quick POC for easier stage 0. It seems to have a lot of offset manipulations so fingers crossed 🤞 for the compiler to get rid of the bound checks. 
It's also awkward to work with the `row` type since it's behind a large `&mut[Channel]` reference.
> Add stage epf

- jxl/src/util/fast_math.rs
before that, a failure could be triggered with 
`ARBTEST_SEED=0xff434b1000010000 cargo test util::fast_math::test::fast_powf_arb`
> less strict fast_powf test

- jxl/src/frame.rs
- jxl/src/frame/group.rs
Drive-by: fix number of contexts when reading HF histograms.
> Support block context maps with quant thresholds.

- jxl/src/enc/mod.rs
- jxl/src/enc/numpy.rs
- jxl/src/features/patches.rs
- jxl/src/frame.rs
- jxl/src/frame/group.rs
- jxl/src/frame/modular.rs
- jxl/src/frame/modular/transforms/apply.rs
- jxl/src/render/test.rs
- jxl/src/util/fast_math.rs
- jxl/src/util/test.rs
- jxl_cli/src/bin/jxlinspect.rs
- jxl_cli/src/main.rs
- jxl_macros/src/lib.rs
Since in vardct mode we pad the group size to 8x8 blocks, this requires a modification to ImageRect::copy_from to allow the source image to be bigger.
> Pass the render pipeline callback to the vardct group decoder.

- jxl/src/frame/quant_weights.rs
- jxl/src/frame/transform_map.rs
10 elements of each quant table is compared to golden data from libjxl, which seemed like a good compromise between checking against golden data and not including 300M golden values.
> Added tests of the quant table computation.

- jxl/src/frame/modular.rs
- jxl/src/image.rs
This is needed since delta palette can have implicit deltas even when num_deltas is 0.
> Allow images with zero width to make delta palette decoding work.

- jxl/src/frame/modular.rs
- jxl/src/frame/modular/transforms/apply.rs
This fixes a crash in the render pipeline for palettized images when we attempt to index output channels by the id of the coded channel.
> Define separate output and coded channel ids in ModularBufferInfo.

- jxl/src/entropy_coding/hybrid_uint.rs
- jxl/src/frame/modular.rs
- jxl/src/frame/modular/decode.rs
- jxl/src/frame/modular/predict.rs
- jxl/src/frame/modular/transforms/palette.rs
- jxl/src/frame/modular/transforms/rct.rs
- jxl/src/frame/modular/tree.rs
Uses wrapping_add and wrapping_sub for i32 operations.
Disable error for reading more than 29 bits for a symbol.
> Fixes for decoding lossless_pfm conformance test image.

- jxl_cli/src/main.rs
Without this
```
cargo run  --bin jxl_cli  -- jxl/resources/test/conformance_test_images/spot.jxl out.ppm
```
fails with misleadning `OutputFormatNotSupported` error.
> add assert for image size check

- jxl/src/frame/group.rs
- jxl/src/headers/frame_header.rs
This does not fix progressive_5 completely, but now we fail on peak error test instead of RMS error test.
> Fix progressive VarDCT: apply shift to non-last passes.

- jxl/src/render/stages/epf.rs
Decreased progressive_5 decoding time from about 6.5s to about 5.1s.
> Unroll Epf0 SAD accumulation loop.

- jxl/src/features/patches.rs
- jxl/src/render/mod.rs
- jxl/src/render/simple_pipeline.rs
- jxl/src/render/stages/blending.rs
- jxl/src/render/stages/chroma_upsample.rs
- jxl/src/render/stages/convert.rs
- jxl/src/render/stages/epf.rs
- jxl/src/render/stages/extend.rs
- jxl/src/render/stages/from_linear.rs
- jxl/src/render/stages/gaborish.rs
- jxl/src/render/stages/nearest_neighbor.rs
- jxl/src/render/stages/noise.rs
- jxl/src/render/stages/patches.rs
- jxl/src/render/stages/save.rs
- jxl/src/render/stages/splines.rs
- jxl/src/render/stages/spot.rs
- jxl/src/render/stages/to_linear.rs
- jxl/src/render/stages/upsample.rs
- jxl/src/render/stages/xyb.rs
- jxl/src/render/stages/ycbcr.rs
- Receive `&self` at `process_row_chunk`.
- Add ability to create and receive thread-local state to `RenderPipelineStage`. Though I'm not sure if this is the best interface...
- Rayon has [`.try_for_each_init()`][rayon] that allows creating thread-local state.
[rayon]: https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.try_for_each_init
> Prepare for multithreaded pipeline runner

- Cargo.lock
- jxl/src/api/decoder.rs
- jxl/src/error.rs
- jxl_cli/Cargo.toml
- jxl_cli/src/bin/jxlinspect.rs
- jxl_cli/src/enc/exr.rs
- jxl_cli/src/enc/png.rs
- jxl_cli/src/main.rs
- jxl_macros/src/lib.rs
- Removed errors from jxl::errors that are only used by CLI tools.
- Made the for_each_test_file macro not require a particular type of Result for the wrapped function.
> Introduced color-eyre into the CLI tools

- jxl/src/api/color.rs
- jxl/src/api/inner/codestream_parser/non_section.rs
- jxl/src/frame.rs
- jxl/src/render/stages/from_linear.rs
- jxl/src/render/stages/to_linear.rs
- jxl/src/render/stages/xyb.rs
This is required for conformance with sections L.2.2 / F.2 of the spec (blending when `save_before_ct` is false).
> Support outputting to non-sRGB colorspaces

- jxl_cli/src/enc/png.rs
Fixes slight mismatch on alpha channel when decoding `candle.jxl` to PNG, listed in #330.
Now `magick identify -verbose` shows the exact same statistics on alpha channel as the image decoded with libjxl. @sboukortt can you confirm that the alpha channels match?
> Round sample values when writing to PNG

- AUTHORS
- jxl/src/image.rs
Hello, 
out of curiosity I ran a flamegraph of jxl_cli with the new `--speedtest` option.
Then I found a weird function call stack with an iterator in the `ImageRect<'a, T>::to_image`.
Here is a proposition to optimise the function by switching from `flat_map/iter` to an explicit loop with
`extend_from_slice`. If this is not relevant I am sorry for the spam.
I ran benchmarks on every conformance_test_images on a mac air m1 with this fish shell command :
```fish
for file in jxl/resources/test/conformance_test_images/*.jxl
set basename (basename $file)
echo "Benchmarking: $basename"
hyperfine -n jxl_cli_opti "./jxl_cli_opti --speedtest $file test.png" -n jxl_cli_main "./jxl_cli_main --speedtest $file test.png" -N --warmup 2
end
```
Here are the results :
File | Optimized Time | Main Time | …
> Refactor row iteration in 'ImageRect::to_image`
