libjxl/jxl-rs

jxl/src/headers/extra_channels.rs, jxl/src/headers/frame_header.rs
Based on comment from @veluca93.
=> Made ExtraChannelInfo.dim_shift private, and added a getter.

.github/workflows/pull_request.yml, Cargo.lock, Cargo.toml, jxl/Cargo.toml, jxl/src/container/mod.rs, jxl/src/container/parse.rs, jxl/src/entropy_coding/decode.rs, jxl/src/headers/bit_depth.rs, jxl/src/headers/color_encoding.rs, jxl/src/headers/encodings.rs, jxl/src/headers/extra_channels.rs, jxl/src/headers/frame_header.rs, jxl/src/headers/image_metadata.rs, jxl/src/headers/mod.rs, jxl/src/headers/size.rs, jxl/src/headers/transform_data.rs, jxl/src/util.rs, jxl/src/util/tracing.rs, jxl_cli/Cargo.toml, jxl_cli/src/bin/jxlinspect.rs, jxl_cli/src/main.rs, jxl_macros/Cargo.toml, jxl_macros/src/lib.rs
This enables logging in (some) tests, and allows disabling logging at compile time with a crate-level feature flag.
Also adds tracing-subscriber as an optional dependency of CLI utilities.
=> Improve logging infrastructure.

Cargo.lock, jxl/Cargo.toml, jxl/src/error.rs, jxl/src/image.rs, jxl/src/render/mod.rs, jxl/src/render/simple_pipeline.rs, jxl/src/render/stages/convert.rs, jxl/src/render/stages/mod.rs, jxl/src/render/stages/save.rs, jxl/src/render/test.rs
Also fixes multiple bugs in the pipeline implementation and adds various utilities to `image`.
=> Add two simple pipeline stages and some tests for the pipeline.

jxl/src/entropy_coding/huffman.rs
=> Fix bugs in Huffman code length decoding

jxl/src/render/internal.rs, jxl/src/render/mod.rs, jxl/src/render/simple_pipeline.rs, jxl/src/render/stages/save.rs
Also updates docs a little bit.
=> Rename `RenderPipelineInputStage` to `RenderPipelineInspectStage`

jxl/src/headers/frame_header.rs, jxl/src/headers/mod.rs, jxl_cli/src/bin/jxlinspect.rs, jxl_cli/src/main.rs
also
rename FileHeaders -> FileHeader
expand two variables named `fh` to avoid confusion between `file_header` and `frame_header`
=> add frame_header_nonserialized to FileHeader

jxl/src/error.rs, jxl/src/icc.rs, jxl/src/icc/header.rs, jxl/src/icc/stream.rs, jxl/src/icc/tag.rs
No tests yet, but it seems to work fine with CMYK profile used in conformance test.
=> Decode ICC profile stream

jxl/src/frame.rs, jxl_macros/src/lib.rs
Currently this panics for some unimplemented stuff: for those we catch the panic if it is known.
=> test reading headers of all testfiles

jxl/src/render/stages/gaborish.rs, jxl/src/render/stages/mod.rs
Implement single-channel Gaborish stage.
=> Gabor-like filter stage

jxl/src/color/tf.rs, jxl/src/util.rs, jxl/src/util/fast_math.rs
Also copied from jxl-oxide which is ported from libjxl.
=> Implement BT.709 transfer function

jxl/src/color/tf.rs
As always, fast conversions are from jxl-oxide ported from libjxl.
=> Implement PQ transfer functions

AUTHORS, jxl/src/render/stages/mod.rs, jxl/src/render/stages/ycbcr.rs
CLA was signed a long time ago with this GitHub username.
=> Add stage ycbcr

jxl_macros/src/lib.rs
Instead, this uses the tracing wrappers, allowing one to do i.e.
RUST_LOG=jxl::headers=trace cargo run --release --bin jxl_cli --features tracing-subscriber -- img-e1.jxl
=> Remove the #[trace] attribute from header reading.

jxl/src/headers/frame_header.rs, jxl/src/util/test.rs
.. in order to reuse it in different places.
=> move `read_frame_header_and_toc`

Cargo.lock, jxl/Cargo.toml, jxl/src/frame.rs, jxl/src/frame/block_context_map.rs, jxl/src/frame/coeff_order.rs, jxl/src/frame/transform_map.rs, jxl/src/headers/permutation.rs, jxl/src/lib.rs, jxl_cli/src/main.rs
Custon weight matrices are not yet supported.
=> Add parser for most of HfGlobal section.

jxl/src/frame/modular.rs, jxl/src/frame/modular/borrowed_buffers.rs, jxl/src/frame/modular/decode.rs, jxl/src/frame/modular/transforms.rs, jxl/src/frame/modular/transforms/apply.rs, jxl/src/frame/modular/transforms/palette.rs, jxl/src/frame/modular/transforms/rct.rs, jxl/src/frame/modular/transforms/squeeze.rs, jxl/src/frame/modular/tree.rs
First step towards local transforms; also simplifies transform implementation.
=> Refactor modular buffer interfaces to be more (re)usable.

jxl/src/bit_reader.rs, jxl/src/frame.rs, jxl/src/frame/modular/decode.rs
Also fixes some incorrect accounting of bits in BitReader::split_at.
=> Add some more debug output and utilities.

jxl/src/frame.rs, jxl/src/frame/modular.rs, jxl/src/frame/modular/transforms/apply.rs, jxl/src/frame/modular/transforms/rct.rs, jxl/src/headers/frame_header.rs, jxl/src/image.rs, jxl/src/render/mod.rs, jxl/src/render/simple_pipeline.rs, jxl/src/render/test.rs, jxl_cli/src/main.rs
Also change the render pipeline interface to accept channel-by-channel data, and fix a few uncovered bugs.
=> Wire up the render pipeline.

jxl/src/var_dct/dct.rs, jxl/src/var_dct/dct_slow.rs
https://github.com/libjxl/jxl-rs/pull/108#discussion_r2054007056
=> use vectors in slow dct

jxl/src/features/spline.rs
Subtracted the row x0 from the pixel to render to avoid trying to render outside the buffer.
Should fix #157.
=> Fixed the offset in spline rendering.

jxl/src/error.rs, jxl/src/frame.rs, jxl/src/frame/quant_weights.rs
=> Read the quant matrices from the bitstream

jxl/src/frame/coeff_order.rs, jxl/src/frame/quant_weights.rs, jxl/src/frame/transform_map.rs
as this is the name used for `Identity` in the spec
=> mention Hornuss

jxl/src/headers/encodings.rs
=> use less unreachable

jxl/src/frame.rs, jxl/src/frame/group.rs
=> Support all BlockContextMap types.

jxl/src/features/patches.rs
Patches for row created a Vec to put the found patches in.
The stage now preallocates it during tree calculation.
=> Made the patch stage prealloc necessary structures.

jxl/src/frame.rs, jxl/src/frame/modular.rs, jxl/src/render/simple_pipeline.rs, jxl/src/render/stages/convert.rs, jxl/src/render/stages/save.rs, jxl/src/render/test.rs
Add output scaling to Save stages.
=> Move i32 to f32 conversion for modular channels to render pipeline.

jxl/src/render/simple_pipeline.rs
Fixes the cafe conformance test image.
=> Fix shift direction in render pipeline.

jxl/src/decode.rs, jxl/src/headers/color_encoding.rs, jxl_cli/src/main.rs
Added `--original-icc-out` for the old behavior.
=> Make `--icc-out` produce the data ICC

jxl/src/decode.rs, jxl/src/icc.rs, jxl/src/icc/stream.rs, jxl_cli/src/bin/jxlinspect.rs
=> Make ICC reading incremental

jxl/src/render/stages/epf.rs
This is a preparation for SIMD, the same way as it is done in libjxl.
Decode time of progressive_5 decreased from about 6.9s to about 6.5s.
=> Unroll Epf1 SAD accumulation loop.

jxl/src/render/simple_pipeline.rs
Decoding time decreased for progressive_5 from about 5.1s to about 3.8s.
=> Precompute as_rect().row() and as_rect_mut().row() more often.

jxl/src/simd/mod.rs
Also added support for relative error in assert_all_almost_eq!.
=> Added tests for individual SIMD instructions.

jxl/Cargo.toml, jxl_macros/Cargo.toml
Feel free to suggest further updates, in particular to add people to the list of package authors (or to come up with a better README...)
=> Update Cargo.toml for crates.io.
